language: php
sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4snapshot

install:
    - composer update --prefer-stable --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/phpunit
